cc_library(
    name = "ArrayTree",
    srcs = [
"ArrayTree.cpp",

],
    hdrs = [
"ArrayTree.hpp",

],
deps = [
        "//src/class/Tree:Tree",
        "//src/class/ForestTree:ForestTree",
        "//src/class/FruitTree:FruitTree",
],
    visibility = ["//visibility:public"],
)
