cc_library(
    name = "Employee",
    srcs = [
"Employee.cpp",

],
    hdrs = [
"Employee.hpp",

],
deps = [
        "//src/class/All:All",
        "//src/class/AllSurnames:AllSurnames",
        "//src/class/AllNumbers:AllNumbers",
        

    ],
    visibility = ["//visibility:public"],
)
