## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["Test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/class/Tree:Tree",
        "//src/class/ForestTree:ForestTree",
        "//src/class/FruitTree:FruitTree",
        "//src/class/ArrayTree:ArrayTree",
    ]
)
