## src/fraction/BUILD

cc_library(
    name = "student",
    srcs = [
"Student.cpp",
"StudentAfterFirstSession.cpp",
"StudentAfterSecondSession.cpp",

],
    hdrs = [
"Student.hpp",
"StudentAfterFirstSession.hpp",
"StudentAfterSecondSession.hpp",

],
    visibility = ["//visibility:public"],
)
