## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["Test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/class/Person:Person",
        "//src/class/Professor:Professor",
        "//src/class/Student:Student",
    ]
)
