filegroup(
        name = "data",
        srcs = [
            "delims.txt",
            "emptytFile.txt",
            "NotExistFile.txt",
            "Numbers.txt",
            "result.bin",
            "result.txt",
            "Strings.txt",
            "test_employees.txt",
            "testNames.txt",
            "testNumbers.txt",
            "worstFile.txt",

            ],
        visibility = ["//visibility:public"]
)