cc_binary(
    name = "cpp_app",
    srcs = ["main.cpp"],
    deps = [
        "//src/class/Tree:Tree",
        "//src/class/ForestTree:ForestTree",
        "//src/class/FruitTree:FruitTree",
        "//src/class/ArrayTree:ArrayTree",
    ],
        data = [
        "//src/Files:Files",
    ],
)
