## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["Test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/class/Student:Student",
 "//src/class/StudentAfterFirstSession:StudentAfterFirstSession",
 "//src/class/StudentAfterSecondSession:StudentAfterSecondSession",
    ]
)
