## src/tests/BUILD

cc_test(
    name = "tests",
    srcs = ["Test.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//src/class/Time:Time",
        "//src/class/Train:Train",
       
    ]
)
